#!/usr/bin/env bash

set -euo pipefail

# shellcheck source=lib/output
. ${DOTFILES_PREFIX}/lib/output

h1 "wget"
h2 "Install"

if brew list | egrep -q '^wget$'; then
  h3 "Already installed"
  exit
fi

brew install wget
