#!/usr/bin/env bash

set -euo pipefail

# shellcheck source=lib/output
. ${DOTFILES_PREFIX}/lib/output

if brew list | egrep -q '^(bash(-completion)?)$'; then
  h3 "Already installed"
  exit
fi

brew install bash bash-completion
