#!/usr/bin/env bash

set -euo pipefail

echo
echo "› bash:"
echo "  › Install"

if brew list | egrep -q '^(bash(-completion)?)$'; then
  echo "    › Already installed"
  exit
fi

brew install bash bash-completion
