#!/usr/bin/env bash

set -euo pipefail

# shellcheck source=lib/output
. ${DOTFILES_PREFIX}/lib/output

# shellcheck source=lib/brew
. ${DOTFILES_PREFIX}/lib/brew

if brewIsAppInstalled "(bash(-completion)?)"; then
  h3 "Already installed"
  exit
fi

brewInstallApp bash
brewInstallApp bash-completion
