#!/usr/bin/env bash

set -euo pipefail

# shellcheck source=lib/output
. ${DOTFILES_PREFIX}/lib/output

# shellcheck source=lib/mas
. ${DOTFILES_PREFIX}/lib/mas

if isAppInstalled "Final Cut Pro" && isAppInstalled "Motion" && isAppInstalled "Compressor"; then
  h3 "Already installed"
  exit
fi

installApp "Final Cut Pro"
installApp "Motion"
installApp "Compressor"
