#!/usr/bin/env bash

set -euo pipefail

# shellcheck source=lib/output
. ${DOTFILES_PREFIX}/lib/output

# shellcheck source=lib/mas
. ${DOTFILES_PREFIX}/lib/mas

# 424390742 Compressor (4.4)
# 434290957 Motion (5.4)
# 424389933 Final Cut Pro (10.4)
CompressorID="424390742"
MotionID="434290957"
FCPID="424389933"

if masIsAppInstalledByID "${CompressorID}" && masIsAppInstalledByID "${MotionID}" && masIsAppInstalledByID "${FCPID}"; then
  h3 "Already installed"
  exit
fi

masInstallAppByID "${CompressorID}"
masInstallAppByID "${MotionID}"
masInstallAppByID "${FCPID}"
