#!/usr/bin/env bash

set -euo pipefail

# shellcheck source=lib/output
. ${DOTFILES_PREFIX}/lib/output

# shellcheck source=lib/mas
. ${DOTFILES_PREFIX}/lib/mas

# 424390742 Compressor (4.4)
# 434290957 Motion (5.4)
# 424389933 Final Cut Pro (10.4)

if masIsAppInstalledByID 424389933 && masIsAppInstalledByID 434290957 && masIsAppInstalledByID 424390742; then
  h3 "Already installed"
  exit
fi

masInstallAppByID 424389933
masInstallAppByID 434290957
masInstallAppByID 424390742
