#!/usr/bin/env bash

set -euo pipefail

# shellcheck source=lib/output
. ${DOTFILES_PREFIX}/lib/output

h1 "vim"
h2 "Install"

if brew list | egrep -q '^vim$'; then
  h3 "Already installed"
  exit
fi

brew install vim
