#!/usr/bin/env bash

set -euo pipefail

# Since there's no `readlink -f` behaviour using perl/python is the only way to achieve full path
export DOTFILES_PREFIX=$(dirname $(perl -MCwd -e 'print Cwd::abs_path shift' "$0"))

# shellcheck source=preferences
. "${DOTFILES_PREFIX}/preferences"

# shellcheck source=lib/output
. "${DOTFILES_PREFIX}/lib/output"

# shellcheck source=lib/brew
. "${DOTFILES_PREFIX}/lib/brew"

h1 "Enable sudo for current process run"
sudo -v

# Install Homebrew
if ! isBrewInstalled; then
  h1 "Preconfiguration"
  h2 "Installing Homebrew for further actions"
  ${DOTFILES_PREFIX}/repository/Homebrew/install
fi

for app in $(ls -1 ${DOTFILES_PREFIX}/repository); do
  h1 "${app}"

  if [[ -x "${DOTFILES_PREFIX}/repository/${app}/install" ]]; then
    h2 "Install"
    ${DOTFILES_PREFIX}/repository/${app}/install
  fi

  if [[ -x "${DOTFILES_PREFIX}/repository/${app}/settings" ]]; then
    h2 "Settings"
    ${DOTFILES_PREFIX}/repository/${app}/settings
  fi

  if [[ -f "${DOTFILES_PREFIX}/repository/${app}/rc" ]]; then
    h2 "rc file"
    h3 "$(cp -v ${DOTFILES_PREFIX}/repository/${app}/rc ~/.${app}rc)"
  fi
done
