#!/usr/bin/env bash

set -euo pipefail

# Since there's no `readlink -f` behaviour using perl/python is the only way to achieve full path
export DOTFILES_PREFIX=$(dirname $(perl -MCwd -e 'print Cwd::abs_path shift' "$0"))

# shellcheck source=lib/output
. "${DOTFILES_PREFIX}/lib/output"

# Install Homebrew
if ! which brew >/dev/null 2>&1; then
  ${DOTFILES_PREFIX}/repository/Homebrew/install
fi

for app in $(ls -1 ${DOTFILES_PREFIX}/repository); do
  [[ -x "${DOTFILES_PREFIX}/repository/${app}/install" ]] &&
    ${DOTFILES_PREFIX}/repository/${app}/install

  [[ -x "${DOTFILES_PREFIX}/repository/${app}/settings" ]] &&
    ${DOTFILES_PREFIX}/repository/${app}/settings

  [[ -f "${DOTFILES_PREFIX}/repository/${app}/rc" ]] &&
    h3 "Install rc file: $(cp -v ${DOTFILES_PREFIX}/repository/${app}/rc ~/.${app}rc)"
done
