#!/usr/bin/env bash

set -euo pipefail

echo
echo "› Transmission:"
echo "  › Install"
if brew cask list | egrep -q '^transmission$'; then
  echo "    › Already installed"
  exit
fi

brew cask install transmission
