#!/usr/bin/env bash

set -euo pipefail

# shellcheck source=lib/output
. ${DOTFILES_PREFIX}/lib/output

h2 "Settings"

h3 "Hide the donate message"
defaults write org.m0k.transmission WarningDonate -bool false

h3 "Hide the legal disclaimer"
defaults write org.m0k.transmission WarningLegal -bool false
