#!/usr/bin/env bash

echo "  › Settings"
echo "    › Hide the donate message"
defaults write org.m0k.transmission WarningDonate -bool false

echo "    › Hide the legal disclaimer"
defaults write org.m0k.transmission WarningLegal -bool false
