#!/usr/bin/env bash

set -euo pipefail

# shellcheck source=lib/output
. ${DOTFILES_PREFIX}/lib/output

# shellcheck source=lib/brew
. ${DOTFILES_PREFIX}/lib/brew

if isBrewInstalled; then
  h3 "Already installed"
  exit 0
fi

/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/bbf4a3a8b247c7dba159c3d557cc3853dd764171/install)"
