#!/usr/bin/env bash

set -euo pipefail

# shellcheck source=lib/output
. ${DOTFILES_PREFIX}/lib/output

h1 "Homebrew"
h2 "Install"

if which brew >/dev/null 2>&1; then
  h3 "Already installed"
  exit 0
fi

/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/bbf4a3a8b247c7dba159c3d557cc3853dd764171/install)"
