#!/usr/bin/env bash

set -euo pipefail

export APPS=(
  "Atom"
  "bash"
  "bazel"
  "curl"
  "FinalCutPro"
  "git"
  "input"
  "iTerm2"
  "iWork"
  "macOS"
  "Server"
  "Transmission"
  "vim"
  "wget"
)
