#!/usr/bin/env bash

set -euo pipefail

export APPS=(
  "bash"
  "curl"
  "input"
  "vim"
  "wget"
  "Server"
)

export PREFERENCES_USE_WELCOME_MESSAGE="no"
export PREFERENCES_HOSTNAME_IN_TITLE="yes"
