#!/usr/bin/env bash

set -euo pipefail

# shellcheck source=lib/output
. ${DOTFILES_PREFIX}/lib/output

h3 "Set git user name"
git config --global user.name "Igor Shishkin"

h3 "Set git user email"
git config --global user.email "me@teran.ru"

h3 "Set git default signing key"
git config --global user.signingkey "1DCED2E4"

h3 "Set git to sign commits by default"
git config --global commit.gpgsign "true"

h3 "Set alias for git l"
git config --global alias.l log

h3 "Set alias for git ll"
git config --global alias.ll "log --graph --show-signature"

h3 "Set alias for git lll"
git config --global alias.lll "log --raw --graph --show-signature"

h3 "Set alias for git diff"
git config --global alias.diff "diff --word-diff"

h3 "Set alias for git cm"
git config --global alias.cm "commit --gpg-sign=1DCED2E4"
