#!/usr/bin/env bash

set -euo pipefail

# shellcheck source=lib/output
. ${DOTFILES_PREFIX}/lib/output

# shellcheck source=lib/brew
. ${DOTFILES_PREFIX}/lib/brew

if isAppInstalled curl; then
  h3 "Already installed"
  exit
fi

installApp curl
