#!/usr/bin/env bash

set -euo pipefail

# shellcheck source=lib/output
. ${DOTFILES_PREFIX}/lib/output

# shellcheck source=lib/mas
. ${DOTFILES_PREFIX}/lib/mas

# 409183694 Keynote (7.3.1)
# 409203825 Numbers (4.3.1)
# 409201541 Pages (6.3.1)
KeynoteID="409183694"
NumbersID="409203825"
PagesID="409201541"

if masIsAppInstalledByID "${KeynoteID}" && masIsAppInstalledByID "${NumbersID}" && masIsAppInstalledByID "${PagesID}"; then
  h3 "Already installed"
  exit
fi

masInstallAppByID "${KeynoteID}"
masInstallAppByID "${NumbersID}"
masInstallAppByID "${PagesID}"
