#!/usr/bin/env bash

set -euo pipefail

# shellcheck source=lib/output
. ${DOTFILES_PREFIX}/lib/output

if brew cask list | egrep -q '^iterm2$'; then
  h3 "Already installed"
  exit
fi

brew cask install iterm2
