#!/usr/bin/env bash

set -euo pipefail

# shellcheck source=lib/output
. ${DOTFILES_PREFIX}/lib/output

# shellcheck source=lib/brew-cask
. ${DOTFILES_PREFIX}/lib/brew-cask

if caskIsAppInstalled iterm2; then
  h3 "Already installed"
  exit
fi

caskInstallApp iterm2
