#!/usr/bin/env bash

set -euo pipefail

# shellcheck source=lib/output
. ${DOTFILES_PREFIX}/lib/output

h3 "Finder, Dock & Appearance"

h4 "Set the Finder prefs for showing a few different volumes on the Desktop"
defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -bool true
defaults write com.apple.finder ShowRemovableMediaOnDesktop -bool true

h4 "Disable Dashboard"
defaults write com.apple.dashboard mcx-disabled -bool true

h4 "Show battery percent"
defaults write com.apple.menuextra.battery ShowPercent -bool true

h4 "Use AirDrop over every interface"
defaults write com.apple.NetworkBrowser BrowseAllInterfaces 1

h4 "Minimize apps to the same icon as in dock"
defaults write com.apple.dock minimize-to-application 1

h4 "Set dark interface style"
defaults write NSGlobalDomain AppleInterfaceStyle -string "Dark"

h4 "Disable the warning when changing a file extension"
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

h4 "Require password immediately after sleep or screen saver begins"
defaults write com.apple.screensaver askForPassword -int 1
defaults write com.apple.screensaver askForPasswordDelay -int 0

h4 "Disable smart quotes and smart dashes as they're annoying when typing code"
defaults write NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -bool false
defaults write NSGlobalDomain NSAutomaticDashSubstitutionEnabled -bool false

h4 "Avoid the creation of .DS_Store files on network volumes"
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true

h4 "Display full POSIX path as Finder window title"
defaults write com.apple.finder _FXShowPosixPathInTitle -bool true

h3 "Safari"

h4 "Show the full URL in the address bar (note: this still hides the scheme)"
defaults write com.apple.Safari ShowFullURLInSmartSearchField -bool true

h4 "Set Safari’s home page to about:blank for faster loading"
defaults write com.apple.Safari HomePage -string "about:blank"

h4 "Prevent Safari from opening ‘safe’ files automatically after downloading"
defaults write com.apple.Safari AutoOpenSafeDownloads -bool false

h4 "Hide Safari’s bookmarks bar by default"
defaults write com.apple.Safari ShowFavoritesBar -bool false

h4 "Hide Safari’s sidebar in Top Sites"
defaults write com.apple.Safari ShowSidebarInTopSites -bool false

h4 "Enable the Develop menu and the Web Inspector in Safari"
defaults write com.apple.Safari IncludeDevelopMenu -bool true
defaults write com.apple.Safari WebKitDeveloperExtrasEnabledPreferenceKey -bool true
defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled -bool true

h4 "Disable Safari plug-ins"
defaults write com.apple.Safari WebKitPluginsEnabled -bool false
defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2PluginsEnabled -bool false

h4 "Disable Java in Safari"
defaults write com.apple.Safari WebKitJavaEnabled -bool false
defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2JavaEnabled -bool false

h4 "Block pop-up windows in Safari"
defaults write com.apple.Safari WebKitJavaScriptCanOpenWindowsAutomatically -bool false
defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2JavaScriptCanOpenWindowsAutomatically -bool false

h4 "Enable 'Do Not Track' header in Safari"
defaults write com.apple.Safari SendDoNotTrackHTTPHeader -bool true

h3 "Mac App Store"

h4 "Enable the automatic update check via Mac App Store"
defaults write com.apple.SoftwareUpdate AutomaticCheckEnabled -bool true

h4 "Check for Apple software updates daily, not just once per week"
defaults write com.apple.SoftwareUpdate ScheduleFrequency -int 1

h4 "Download newly available Apple updates in background"
defaults write com.apple.SoftwareUpdate AutomaticDownload -int 1

h3 "Photos & Image Capture"

h4 "Prevent Photos from opening automatically when devices are plugged in"
defaults -currentHost write com.apple.ImageCapture disableHotPlug -bool true

h3 "TextEdit"

h4 "Use plain text mode for new TextEdit documents"
defaults write com.apple.TextEdit RichText -int 0

h4 "Open and save files as UTF-8 in TextEdit"
defaults write com.apple.TextEdit PlainTextEncoding -int 4
defaults write com.apple.TextEdit PlainTextEncodingForWrite -int 4

h3 "Activity Monitor"

h4 "Show the main window when launching Activity Monitor"
defaults write com.apple.ActivityMonitor OpenMainWindow -bool true

h4 "Visualize CPU usage in the Activity Monitor Dock icon"
defaults write com.apple.ActivityMonitor IconType -int 5

h4 "Show all processes in Activity Monitor"
defaults write com.apple.ActivityMonitor ShowCategory -int 0

h4 "Sort Activity Monitor results by CPU usage"
defaults write com.apple.ActivityMonitor SortColumn -string "CPUUsage"
defaults write com.apple.ActivityMonitor SortDirection -int 0

h3 "Hardware & Power Management"

h4 "Turn off keyboard illumination when computer is not used for 5 minutes"
defaults write com.apple.BezelServices kDimTime -int 300

h3 "Time Machine"

h4 "Prevent Time Machine from prompting to use new hard drives as backup volume"
defaults write com.apple.TimeMachine DoNotOfferNewDisksForBackup -bool true
